# Generated by Django 4.1.2 on 2023-06-04 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='editorial',
            fields=[
                ('id_editorial', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomb_editorial', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id_genero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nomb_genero', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id_region', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nomb_region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='manga',
            fields=[
                ('id_manga', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('nro_volumen', models.CharField(max_length=10)),
                ('precio', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('stock', models.CharField(max_length=100, null=True)),
                ('cover', models.ImageField(default='null', upload_to='manga')),
                ('fecha_publicacion', models.DateField()),
                ('sinopsis', models.TextField()),
                ('id_editorial', models.ForeignKey(db_column='id_editorial', on_delete=django.db.models.deletion.CASCADE, to='venta.editorial')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, to='venta.genero')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id_comuna', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('nomb_comuna', models.CharField(max_length=100)),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='venta.region')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('user', models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.comuna')),
            ],
        ),
    ]
