# Generated by Django 4.2.1 on 2023-05-31 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover',
            field=models.ImageField(default='null', upload_to='manga'),
        ),
        migrations.AddField(
            model_name='manga',
            name='stock',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
